M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-08-15T18:35:22+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-08-15T18:35:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
%
G90
G05
T1
X5.313Y-3.5846
X5.353Y-3.8846
X5.393Y-3.5846
M30
