M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-08-15T18:29:22+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-15T18:29:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
%
G90
G05
T1
X134.949Y-91.05
X135.965Y-98.67
X136.981Y-91.05
M30
